name: Build and Publish to Repo

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleWebApp.csproj

      - name: Build app
        run: dotnet build SimpleWebApp.csproj --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish SimpleWebApp.csproj --configuration Release --output ./published

      - name: Upload published app artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./published

    #   - name: Run Terraform Simulation
    #     run: |
    #       terraform init
    #       terraform apply -auto-approve