name: Build and Publish to Repo

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleWebApp.csproj

      - name: Build app
        run: dotnet build SimpleWebApp.csproj --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish SimpleWebApp.csproj --configuration Release --output ./published

      - name: Upload published app artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./published

          
      # Following is an example of how to deploy to IIS, commented out for now
     

      # - name: Deploy to IIS
      #   shell: pwsh
      #   run: |
      #     $iisPath = 'C:\inetpub\wwwroot\SimpleWebApp'
      #     if (Test-Path $iisPath) {
      #       Remove-Item -Recurse -Force $iisPath\*
      #     } else {
      #       New-Item -ItemType Directory -Path $iisPath
      #     }
      #     Copy-Item -Path './published/*' -Destination $iisPath -Recurse
      #     Import-Module WebAdministration
      #     Restart-WebAppPool -Name 'DefaultAppPool'

